<a href="https://www.kaggle.com/code/diegorestrepoleal/eda-sales-time-series-forecasting?scriptVersionId=355293832" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
library(tidyverse)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.2

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [2]:
minmax_date <- function(df, date="date") {
    df %>%
        select(date) %>%
        summarise(`Date min` = min(date),
              `Date max` = max(date)
        )    
}

# Holidays Events

In [3]:
df_holidays_events <- read_csv("/kaggle/input/competitions/store-sales-time-series-forecasting/holidays_events.csv")
df_holidays_events %>%
    head()

Rows: 350 Columns: 6

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (4): type, locale, locale_name, description
lgl  (1): transferred
date (1): date

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  date       type    locale   locale_name description
1 2012-03-02 Holiday Local    Manta       Fundacion de Manta
2 2012-04-01 Holiday Regional Cotopaxi    Provincializacion de Cotopaxi
3 2012-04-12 Holiday Local    Cuenca      Fundacion de Cuenca
4 2012-04-14 Holiday Local    Libertad    Cantonizacion de Libertad
5 2012-04-21 Holiday Local    Riobamba    Cantonizacion de Riobamba
6 2012-05-12 Holiday Local    Puyo        Cantonizacion del Puyo
  transferred
1 FALSE
2 FALSE
3 FALSE
4 FALSE
5 FALSE
6 FALSE

In [4]:
df_holidays_events %>%
    minmax_date()

  Date min   Date max
1 2012-03-02 2017-12-26

# Oil

In [5]:
df_oil <- read_csv("/kaggle/input/competitions/store-sales-time-series-forecasting/oil.csv")
df_oil %>%
    head()

Rows: 1218 Columns: 2

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl  (1): dcoilwtico
date (1): date

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  date       dcoilwtico
1 2013-01-01    NA
2 2013-01-02 93.14
3 2013-01-03 92.97
4 2013-01-04 93.12
5 2013-01-07 93.20
6 2013-01-08 93.21

In [6]:
df_oil %>%
    minmax_date()

  Date min   Date max
1 2013-01-01 2017-08-31

# Stores

In [7]:
df_stores <- read_csv("/kaggle/input/competitions/store-sales-time-series-forecasting/stores.csv")
df_stores %>%
    head()

Rows: 54 Columns: 5

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (3): city, state, type
dbl (2): store_nbr, cluster

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  store_nbr city          state                          type cluster
1 1         Quito         Pichincha                      D    13
2 2         Quito         Pichincha                      D    13
3 3         Quito         Pichincha                      D     8
4 4         Quito         Pichincha                      D     9
5 5         Santo Domingo Santo Domingo de los Tsachilas D     4
6 6         Quito         Pichincha                      D    13

# Transactions

In [8]:
df_transactions <- read_csv("/kaggle/input/competitions/store-sales-time-series-forecasting/transactions.csv")
df_transactions %>%
    head()

Rows: 83488 Columns: 3

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl  (2): store_nbr, transactions
date (1): date

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  date       store_nbr transactions
1 2013-01-01 25         770
2 2013-01-02  1        2111
3 2013-01-02  2        2358
4 2013-01-02  3        3487
5 2013-01-02  4        1922
6 2013-01-02  5        1903

In [9]:
df_transactions %>%
    minmax_date()

  Date min   Date max
1 2013-01-01 2017-08-15

# Train

In [10]:
df_train <- read_csv("/kaggle/input/competitions/store-sales-time-series-forecasting/train.csv")
df_train %>%
    head()

Rows: 3000888 Columns: 6

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (1): family
dbl  (4): id, store_nbr, sales, onpromotion
date (1): date

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  id date       store_nbr family       sales onpromotion
1 0  2013-01-01 1         AUTOMOTIVE   0     0
2 1  2013-01-01 1         BABY CARE    0     0
3 2  2013-01-01 1         BEAUTY       0     0
4 3  2013-01-01 1         BEVERAGES    0     0
5 4  2013-01-01 1         BOOKS        0     0
6 5  2013-01-01 1         BREAD/BAKERY 0     0

In [11]:
df_train %>%
    minmax_date()

  Date min   Date max
1 2013-01-01 2017-08-15

# Test

In [12]:
df_test <- read_csv("/kaggle/input/competitions/store-sales-time-series-forecasting/test.csv")
df_test %>%
    head()

Rows: 28512 Columns: 5

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (1): family
dbl  (3): id, store_nbr, onpromotion
date (1): date

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  id      date       store_nbr family       onpromotion
1 3000888 2017-08-16 1         AUTOMOTIVE    0
2 3000889 2017-08-16 1         BABY CARE     0
3 3000890 2017-08-16 1         BEAUTY        2
4 3000891 2017-08-16 1         BEVERAGES    20
5 3000892 2017-08-16 1         BOOKS         0
6 3000893 2017-08-16 1         BREAD/BAKERY 12

# Sample submission

In [13]:
df_sample_submission <- read_csv("/kaggle/input/competitions/store-sales-time-series-forecasting/sample_submission.csv")
df_sample_submission %>%
    head()

Rows: 28512 Columns: 2

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (2): id, sales

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  id      sales
1 3000888 0
2 3000889 0
3 3000890 0
4 3000891 0
5 3000892 0
6 3000893 0